# Generated by Django 3.2.5 on 2022-02-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catchCO2', '0006_alter_gpsinfo_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpsinfo',
            name='transport',
            field=models.FloatField(default=0),
        ),
    ]
